# Name of the workflow
name: Scrape Twitter Trends

on:
  # Schedule to run at minute 0 of every 3rd hour (UTC)
  schedule:
    - cron: '0 */3 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  scrape-and-update:
    # Always specify the runner type
    runs-on: ubuntu-latest
    steps:
      # 1. CRITICAL: Checks out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. CRITICAL: Sets up the Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Installs the required Python libraries
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. CRITICAL: Download TextBlob Corpora
      # TextBlob needs these files for sentiment analysis.
      - name: Download TextBlob Corpora
        run: python -m textblob.download_corpora

      # 5. Run your Python scraper script
      - name: Run Scraper
        run: python t3_scraper.py
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}